name: Create zip release

# This workflow is triggered on pushes to /files directory
on:
  push:
    paths: 'files/**'


jobs:
 # Job 1
 build:
    name: build
    # This job runs on latest Windows container
    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.1.0
    - run: dir
      shell: cmd
    - name: Display Powershell Version
      run: $PSVersionTable
      shell: powershell
    - name: Create ZIP
      run: '. .\CreateZipFile.ps1'
      shell: powershell
    - run: dir
      shell: cmd

 # Job 2
 test:
   needs: [build]
   name: test zip file
   runs-on: windows-latest
   defaults:
     run:
       shell: powershell
   env:
     FILENAME: files.zip
     EXTRACTPATH: ./extractzip
   steps:
     - run: dir
       shell: cmd
     - name: Check zip file exists
       run: If(Test-path $FILENAME) {write-host "Zip file found"}
     - name: Test file extraction
       run: Expand-Archive -Path $FILENAME -DestinationPath $EXTRACTPATH
     - name: tree listing for log verification
       run: Get-ChildItem $EXTRACTPATH
