name: Create zip release

# This workflow is triggered on pushes to /files directory
on:
  push:
    paths: 'files/**'


jobs:
 # Job 1
 build:
    name: build and upload release
    # This job runs on latest Windows container
    runs-on: windows-latest
    # Default shell language for job
    defaults:
      run:
        shell: powershell
    # Environment variables for job
    env:
      FILENAME: files.zip
      EXTRACTPATH: ./extractzip
    # Steps definition
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.1.0
    - run: Get-ChildItem
    - name: Display Powershell Version
      run: $PSVersionTable
    - name: Create ZIP
      run: '. .\CreateZipFile.ps1'
    - run: Get-ChildItem
    - name: Check zip file exists
      run: If(Test-path $env:FILENAME) {write-host "Zip file found"}
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release generated by Github Actions automatically
        draft: false
        prerelease: true
    - name: Upload Release Asset
      id: release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./files.zip
        asset_name: myfiles.zip
        asset_content_type: application/zip

 # Job 2
 test:
   needs: [build]
   name: test zip file
   runs-on: windows-latest
   defaults:
     run:
       shell: powershell
   env:
     ASSETID: ${{ steps.release_asset.outputs.id }}
     DNLDURL: ${{ steps.release_asset.outputs.browser_download_url }}
   steps:
     - run: echo AssetID = %ASSETID%
       shell: cmd
     - run: write-host $env:DNLDURL

 # Job 3
# release:
#   runs-on: ubuntu-latest
#   needs: [test]
#   name: publish release
#   steps:
#     - name: change release status
#       uses: 
